name: memory
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.20.1
  cupertino_icons: ^1.0.2
  go_router: ^3.0.1
  logging: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  collection: ^1.16.0

  firebase_core: ^1.15.0  # Needed for Crashlytics below
  firebase_crashlytics: ^2.8.1  # Error reporting
  games_services: ^2.0.7  # Achievements and leaderboards
  google_mobile_ads: ^1.1.0  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/cards/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
